# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envsecrets < Formula
  desc ""
  homepage "https://github.com/envsecrets/envsecrets"
  version "0.0.6"

  on_macos do
    url "https://github.com/envsecrets/envsecrets/releases/download/v0.0.6/envsecrets_0.0.6_darwin_all.tar.gz"
    sha256 "1fdf66b12b768fe70a694b0ddb68772e4736d2ce490b934968c88b521d71c5fe"

    def install
      bin.install "envsecrets"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/envsecrets/envsecrets/releases/download/v0.0.6/envsecrets_0.0.6_linux_amd64.tar.gz"
      sha256 "f6fcc6948102423ee1e366210ed827b8f0dadc1565d81960859387aae8aec00a"

      def install
        bin.install "envsecrets"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/envsecrets/envsecrets/releases/download/v0.0.6/envsecrets_0.0.6_linux_arm64.tar.gz"
      sha256 "a39efe5283bb45da79554cbaf8080c56bdcd9b779eaa7f1108d13887b8d576f6"

      def install
        bin.install "envsecrets"
      end
    end
  end
end
